spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdemo
    username: root
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

bezkoder:
    app:   
      jwtSecret: "bezKoderSecretKey"     
      jwtExpirationMs: 86400000
      