spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdemo
    username: root
    password: password
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

#jwtExpirationMs -> 60000 = 1 minutes
bezkoder:
    app:   
      jwtSecret: "bezKoderSecretKey"     
      jwtExpirationMs: 60000
      